CREATE TABLE Manufacturer (
	MANUFACTURER_ID INT NOT NULL AUTO_INCREMENT,
	PLASTIC_TYPE INT NOT NULL,
	MANUFACTURER_NAME TEXT,
	PRICE_PER_G FLOAT NOT NULL,
	PRIMARY KEY (MANUFACTURER_ID)
);

CREATE TABLE Stock (
	STOCK_ID INT NOT NULL AUTO_INCREMENT,
	PLASTIC_TYPE INT NOT NULL,
	MANUFACTURER INT NOT NULL,
	STOCK_IN_G INT NOT NULL DEFAULT '0',
	PRIMARY KEY (STOCK_ID)
);

CREATE TABLE Maintainer (
	MAINTAINER_ID INT NOT NULL AUTO_INCREMENT,
	MAINTAINER_NAME TEXT NOT NULL,
	SALARY INT NOT NULL,
	EXPENSES INT NOT NULL DEFAULT '0',
	PRIMARY KEY (MAINTAINER_ID)
);

CREATE TABLE 3D_Printer (
	PRINTER_ID INT NOT NULL AUTO_INCREMENT,
	PRINTER_NAME VARCHAR(255) NOT NULL,
	MAINTAINER_ID INT NOT NULL,
	PRINTER_PRICE INT NOT NULL DEFAULT '0',
	PRINTER_FLOW FLOAT NOT NULL DEFAULT '10',
	PRIMARY KEY (PRINTER_ID)
);

CREATE TABLE Modell (
	MODELL_ID INT NOT NULL AUTO_INCREMENT,
	MODELL_NAME TEXT,
	MODELL_LINK TEXT,
	PLASTIC_REQUIRED INT NOT NULL,
	LICENSE_FEE INT NOT NULL DEFAULT '0',
	PRIMARY KEY (MODELL_ID)
);

CREATE TABLE Shopping_cart (
	CART_ID INT NOT NULL,
	MODELL_ID INT NOT NULL,
	QUANTITY INT NOT NULL DEFAULT '1',
	PRIMARY KEY (CART_ID,MODELL_ID)
);

CREATE TABLE Orders (
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_ID INT NOT NULL,
	PRINTER_ID INT NOT NULL,
	PLASTIC_TYPE INT NOT NULL,
	CART_ID INT NOT NULL,
	ORDER_PRICE INT NOT NULL DEFAULT '0',
	ORDER_PRIORITY INT NOT NULL DEFAULT '0',
	MANUFACTURED BINARY NOT NULL DEFAULT '0',
	SHIPPED BINARY NOT NULL DEFAULT '0',
	DELIVERED BINARY NOT NULL DEFAULT '0',
	FAILED BINARY NOT NULL DEFAULT '0',
	PRIMARY KEY (ORDER_ID)
);

CREATE TABLE Complaints (
	COMPLAINT_ID INT NOT NULL AUTO_INCREMENT,
	ORDER_ID INT NOT NULL,
	REASON TEXT NOT NULL,
	PRIMARY KEY (COMPLAINT_ID)
);

CREATE TABLE Customer (
	CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_NAME TEXT NOT NULL,
	SHIPPING_INFO_ID INT NOT NULL,
	BANK_CARD_INFO TEXT,
	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE Shipping_info (
	SHIPPING_INFO_ID INT NOT NULL AUTO_INCREMENT,
	COUNTRY TEXT NOT NULL,
	CITY TEXT NOT NULL,
	STREET TEXT NOT NULL,
	STREET_NO INT NOT NULL,
	OTHER TEXT NOT NULL,
	PRIMARY KEY (SHIPPING_INFO_ID)
);

CREATE TABLE Plastic (
	PLASTIC_ID INT NOT NULL AUTO_INCREMENT,
	PLASTIC_NAME VARCHAR(255) NOT NULL,
	MELTING_POINT INT NOT NULL,
	PRIMARY KEY (PLASTIC_ID)
);

ALTER TABLE Manufacturer ADD CONSTRAINT Manufacturer_fk0 FOREIGN KEY (PLASTIC_TYPE) REFERENCES Plastic(PLASTIC_ID);

ALTER TABLE Stock ADD CONSTRAINT Stock_fk0 FOREIGN KEY (PLASTIC_TYPE) REFERENCES Plastic(PLASTIC_ID);

ALTER TABLE Stock ADD CONSTRAINT Stock_fk1 FOREIGN KEY (MANUFACTURER) REFERENCES Manufacturer(MANUFACTURER_ID);

ALTER TABLE 3D_Printer ADD CONSTRAINT 3D_Printer_fk0 FOREIGN KEY (MAINTAINER_ID) REFERENCES Maintainer(MAINTAINER_ID);

ALTER TABLE Shopping_cart ADD CONSTRAINT Shopping_cart_fk0 FOREIGN KEY (MODELL_ID) REFERENCES Modell(MODELL_ID);

ALTER TABLE Orders ADD CONSTRAINT Orders_fk0 FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID);

ALTER TABLE Orders ADD CONSTRAINT Orders_fk1 FOREIGN KEY (PRINTER_ID) REFERENCES 3D_Printer(PRINTER_ID);

ALTER TABLE Orders ADD CONSTRAINT Orders_fk2 FOREIGN KEY (PLASTIC_TYPE) REFERENCES Plastic(PLASTIC_ID);

ALTER TABLE Orders ADD CONSTRAINT Orders_fk3 FOREIGN KEY (CART_ID) REFERENCES Shopping_cart(CART_ID);

ALTER TABLE Complaints ADD CONSTRAINT Complaints_fk0 FOREIGN KEY (ORDER_ID) REFERENCES Orders(ORDER_ID);

ALTER TABLE Customer ADD CONSTRAINT Customer_fk0 FOREIGN KEY (SHIPPING_INFO_ID) REFERENCES Shipping_info(SHIPPING_INFO_ID);

